"""Initial migration

Revision ID: be400339d8b0
Revises: 
Create Date: 2024-11-13 00:29:57.037683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be400339d8b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pollution_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('water_quality_index', sa.Integer(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pollution_data_date'), 'pollution_data', ['date'], unique=False)
    op.create_index(op.f('ix_pollution_data_id'), 'pollution_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pollution_data_id'), table_name='pollution_data')
    op.drop_index(op.f('ix_pollution_data_date'), table_name='pollution_data')
    op.drop_table('pollution_data')
    # ### end Alembic commands ###
